### PR TITLE
Updated. Now it works

### PR DESCRIPTION
**Pull request by DopustimVladimir**
The package "coffee-script" replaced by "coffeescript" and "uglify-js" by "uglify-es". Also updated "mkdirp" and "resolve" packages. Solved the problem with destructuring assignment.

Thank you, @olmokramer for your plugin.

[I would like to take your repo](https://github.com/olmokramer/atom-coffee-autocompile/issues/12#issuecomment-462047516)

### CODE REVIEW

**Comment by olmokramer** [comment]
Hi Vladimir, thanks for your interest in continuing this plugin! I've added you as a collaborator to the repository so you can merge this. I also tried to transfer the repository to your account, but I got an error message that [DopustimVladimir/atom-coffee-autocompile](https://github.com/DopustimVladimir/atom-coffee-autocompile) already exists (which isn't all that surprising, as you've forked to make the PR). I'll try to remember to transfer again after you've merged this and had a chance to delete your fork, please do post a reminder here if I forget to do so within a few days.
Cheers!

**Comment by DopustimVladimir** [comment]
@olmokramer

Nice! I'm ready

**Comment by olmokramer** [comment]
That was fast! Seems to have worked this time. Good luck with the maintainance!

**Comment by DopustimVladimir** [comment]
@olmokramer, thanks! I will try my best )) Will you publish this plugin? You can also remove it from atom packages, then I will be able to create it again. Seems that you cannot transfer:
https://atom.io/packages/coffee-autocompile

**Comment by olmokramer** [comment]
@DopustimVladimir I've unpublished the plugin now. If all is well you should be able to publish now.

**Comment by DopustimVladimir** [comment]
Nice! Works good

**Pull request merged**
